# Generated by Django 5.0.6 on 2024-07-11 16:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('createur', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateField(default=datetime.datetime.now)),
                ('disponible', models.BooleanField(default=True)),
                ('realisateur', models.CharField(max_length=150)),
                ('emprunteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire_app.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateField(default=datetime.datetime.now)),
                ('disponible', models.BooleanField(default=True)),
                ('artiste', models.CharField(max_length=150)),
                ('emprunteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire_app.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateField(default=datetime.datetime.now)),
                ('disponible', models.BooleanField(default=True)),
                ('auteur', models.CharField(max_length=150)),
                ('emprunteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire_app.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
