# Generated by Django 5.0.6 on 2024-07-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprunteur',
            new_name='Membre',
        ),
        migrations.RenameField(
            model_name='cd',
            old_name='emprunteur',
            new_name='membre',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='emprunteur',
            new_name='membre',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='emprunteur',
            new_name='membre',
        ),
    ]
