# Generated by Django 5.0.6 on 2024-07-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire_app', '0003_remove_cd_dateemprunt_remove_cd_membre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='nom',
            new_name='name',
        ),
    ]
