# Generated by Django 5.0.6 on 2024-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire_app', '0004_rename_nom_cd_name_rename_nom_dvd_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='membres',
            field=models.ManyToManyField(related_name='livres', through='bibliothecaire_app.Emprunteur', to='bibliothecaire_app.membre'),
        ),
    ]
