# Generated by Django 5.0.6 on 2024-07-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire_app', '0005_alter_livre_membres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='membres',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='membres',
        ),
        migrations.RemoveField(
            model_name='emprunteur',
            name='cd',
        ),
        migrations.RemoveField(
            model_name='emprunteur',
            name='dvd',
        ),
    ]
