# Generated by Django 5.0.6 on 2024-07-13 14:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire_app', '0006_remove_cd_membres_remove_dvd_membres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='NbEmprunt',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmpruntCd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmprunt', models.DateField(default=datetime.datetime.now)),
                ('dateRemis', models.DateField(default=datetime.datetime.now)),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire_app.cd')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire_app.membre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cd',
            name='membres',
            field=models.ManyToManyField(related_name='cds', through='bibliothecaire_app.EmpruntCd', to='bibliothecaire_app.membre'),
        ),
        migrations.CreateModel(
            name='EmpruntDvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmprunt', models.DateField(default=datetime.datetime.now)),
                ('dateRemis', models.DateField(default=datetime.datetime.now)),
                ('dvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire_app.dvd')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire_app.membre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dvd',
            name='membres',
            field=models.ManyToManyField(related_name='dvds', through='bibliothecaire_app.EmpruntDvd', to='bibliothecaire_app.membre'),
        ),
        migrations.CreateModel(
            name='EmpruntLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmprunt', models.DateField(default=datetime.datetime.now)),
                ('dateRemis', models.DateField(default=datetime.datetime.now)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire_app.livre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire_app.membre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='livre',
            name='membres',
            field=models.ManyToManyField(related_name='livres', through='bibliothecaire_app.EmpruntLivre', to='bibliothecaire_app.membre'),
        ),
        migrations.DeleteModel(
            name='Emprunteur',
        ),
    ]
