# Generated by Django 5.0.6 on 2024-07-14 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire_app', '0008_remove_empruntcd_dateremis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empruntcd',
            name='dateEmprunt_max',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='empruntdvd',
            name='dateEmprunt_max',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='empruntlivre',
            name='dateEmprunt_max',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
