# Generated by Django 5.0.6 on 2024-07-14 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire_app', '0009_empruntcd_dateemprunt_max_empruntdvd_dateemprunt_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empruntcd',
            name='dateEmprunt',
            field=models.DateField(default=datetime.date(2024, 7, 14)),
        ),
        migrations.AlterField(
            model_name='empruntcd',
            name='dateEmprunt_max',
            field=models.DateField(default=datetime.date(2024, 7, 21)),
        ),
        migrations.AlterField(
            model_name='empruntdvd',
            name='dateEmprunt',
            field=models.DateField(default=datetime.date(2024, 7, 14)),
        ),
        migrations.AlterField(
            model_name='empruntdvd',
            name='dateEmprunt_max',
            field=models.DateField(default=datetime.date(2024, 7, 21)),
        ),
        migrations.AlterField(
            model_name='empruntlivre',
            name='dateEmprunt',
            field=models.DateField(default=datetime.date(2024, 7, 14)),
        ),
        migrations.AlterField(
            model_name='empruntlivre',
            name='dateEmprunt_max',
            field=models.DateField(default=datetime.date(2024, 7, 21)),
        ),
    ]
