# Generated by Django 5.0.6 on 2024-07-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire_app', '0010_alter_empruntcd_dateemprunt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='membres',
        ),
        migrations.RemoveField(
            model_name='empruntcd',
            name='cd',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='membres',
        ),
        migrations.RemoveField(
            model_name='empruntdvd',
            name='dvd',
        ),
        migrations.RemoveField(
            model_name='empruntcd',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='empruntdvd',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='empruntlivre',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='empruntlivre',
            name='membre',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='membres',
        ),
        migrations.DeleteModel(
            name='JeuDePlateau',
        ),
        migrations.DeleteModel(
            name='Cd',
        ),
        migrations.DeleteModel(
            name='Dvd',
        ),
        migrations.DeleteModel(
            name='EmpruntCd',
        ),
        migrations.DeleteModel(
            name='EmpruntDvd',
        ),
        migrations.DeleteModel(
            name='EmpruntLivre',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
        migrations.DeleteModel(
            name='Membre',
        ),
    ]
